import random
from .db import get_db


def seed():
    db = get_db()
    db.books.delete_many({})
    db.inventory.delete_many({})

    books = [
        {
            "title": "Starlight Explorers",
            "author": "J. Vega",
            "description": "A crew of kids explore new planets with a curious robot friend.",
            "tags": ["space", "science", "adventure"],
            "age_min": 7,
            "age_max": 10,
            "reading_level": "middle",
            "language": "English",
            "format": "chapter",
            "cover_url": "",
            "isbn": "111000000001",
        },
        {
            "title": "Paws on Parade",
            "author": "L. Hart",
            "description": "Picture book about rescue dogs helping a town parade.",
            "tags": ["animals", "community"],
            "age_min": 3,
            "age_max": 6,
            "reading_level": "early",
            "language": "English",
            "format": "picture",
            "cover_url": "",
            "isbn": "111000000002",
        },
        {
            "title": "The Moon Tree Mystery",
            "author": "S. Quinn",
            "description": "A detective club solves a mystery at space camp.",
            "tags": ["mystery", "space"],
            "age_min": 8,
            "age_max": 12,
            "reading_level": "middle",
            "language": "English",
            "format": "chapter",
            "cover_url": "",
            "isbn": "111000000003",
        },
        {
            "title": "Goal Line Heroes",
            "author": "M. Cruz",
            "description": "A soccer team learns teamwork and fair play.",
            "tags": ["sports"],
            "age_min": 6,
            "age_max": 9,
            "reading_level": "early",
            "language": "English",
            "format": "chapter",
            "cover_url": "",
            "isbn": "111000000004",
        },
        {
            "title": "Galaxy Garden",
            "author": "A. Patel",
            "description": "Picture book about a kid who grows plants in space.",
            "tags": ["space", "science"],
            "age_min": 4,
            "age_max": 7,
            "reading_level": "early",
            "language": "English",
            "format": "picture",
            "cover_url": "",
            "isbn": "111000000005",
        },
        {
            "title": "Tracks and Clues",
            "author": "N. Reed",
            "description": "A mystery at the train museum with a clever cat.",
            "tags": ["mystery", "animals"],
            "age_min": 7,
            "age_max": 10,
            "reading_level": "middle",
            "language": "English",
            "format": "chapter",
            "cover_url": "",
            "isbn": "111000000006",
        },
        {
            "title": "The Big Dino Dig",
            "author": "K. James",
            "description": "Dinosaurs and fossils in a lively picture book.",
            "tags": ["animals", "science"],
            "age_min": 3,
            "age_max": 6,
            "reading_level": "early",
            "language": "English",
            "format": "picture",
            "cover_url": "",
            "isbn": "111000000007",
        },
        {
            "title": "Mystery of the Missing Mascot",
            "author": "T. Brooks",
            "description": "School sleuths search for the missing mascot before the game.",
            "tags": ["mystery", "sports"],
            "age_min": 8,
            "age_max": 12,
            "reading_level": "middle",
            "language": "English",
            "format": "chapter",
            "cover_url": "",
            "isbn": "111000000008",
        },
        {
            "title": "Space Station Sleepover",
            "author": "R. Kim",
            "description": "A fun graphic novel about kids at a space station.",
            "tags": ["space", "science"],
            "age_min": 8,
            "age_max": 12,
            "reading_level": "middle",
            "language": "English",
            "format": "graphic",
            "cover_url": "",
            "isbn": "111000000009",
        },
        {
            "title": "Animal Rescue Rangers",
            "author": "B. Lopez",
            "description": "Chapter book about kids helping animals find new homes.",
            "tags": ["animals", "community"],
            "age_min": 7,
            "age_max": 10,
            "reading_level": "middle",
            "language": "English",
            "format": "chapter",
            "cover_url": "",
            "isbn": "111000000010",
        },
        {
            "title": "Hoops and Hurdles",
            "author": "D. Turner",
            "description": "Graphic novel about a basketball team overcoming obstacles.",
            "tags": ["sports"],
            "age_min": 9,
            "age_max": 12,
            "reading_level": "middle",
            "language": "English",
            "format": "graphic",
            "cover_url": "",
            "isbn": "111000000011",
        },
        {
            "title": "Secret of the Silent Library",
            "author": "C. Moore",
            "description": "Mystery in a spooky old library.",
            "tags": ["mystery"],
            "age_min": 9,
            "age_max": 12,
            "reading_level": "middle",
            "language": "English",
            "format": "chapter",
            "cover_url": "",
            "isbn": "111000000012",
        },
        {
            "title": "Wildlife Wonders",
            "author": "E. Singh",
            "description": "Nonfiction picture book about animals around the world.",
            "tags": ["animals"],
            "age_min": 4,
            "age_max": 7,
            "reading_level": "early",
            "language": "English",
            "format": "picture",
            "cover_url": "",
            "isbn": "111000000013",
        },
        {
            "title": "Rocket Raccoon and the Lost Map",
            "author": "S. Liao",
            "description": "A raccoon astronaut searches for a lost star map.",
            "tags": ["space", "animals"],
            "age_min": 6,
            "age_max": 9,
            "reading_level": "early",
            "language": "English",
            "format": "picture",
            "cover_url": "",
            "isbn": "111000000014",
        },
        {
            "title": "The Great Sports Mix-Up",
            "author": "H. Green",
            "description": "Humorous chapter book about trying different sports.",
            "tags": ["sports"],
            "age_min": 7,
            "age_max": 10,
            "reading_level": "middle",
            "language": "English",
            "format": "chapter",
            "cover_url": "",
            "isbn": "111000000015",
        },
        {
            "title": "Detective Daisy and the Vanishing Treats",
            "author": "P. Allen",
            "description": "Mystery picture book with a clever dog detective.",
            "tags": ["mystery", "animals"],
            "age_min": 4,
            "age_max": 7,
            "reading_level": "early",
            "language": "English",
            "format": "picture",
            "cover_url": "",
            "isbn": "111000000016",
        },
        {
            "title": "Snowy Peak Adventure",
            "author": "J. Ortiz",
            "description": "Kids explore a mountain and learn about wildlife.",
            "tags": ["animals", "adventure"],
            "age_min": 7,
            "age_max": 10,
            "reading_level": "middle",
            "language": "English",
            "format": "chapter",
            "cover_url": "",
            "isbn": "111000000017",
        },
        {
            "title": "Space Cat and the Comet",
            "author": "M. Watanabe",
            "description": "Graphic novel about a cat astronaut and a runaway comet.",
            "tags": ["space", "animals"],
            "age_min": 8,
            "age_max": 12,
            "reading_level": "middle",
            "language": "English",
            "format": "graphic",
            "cover_url": "",
            "isbn": "111000000018",
        },
        {
            "title": "Little Farm Friends",
            "author": "G. Rivera",
            "description": "Picture book about animals helping each other on a farm.",
            "tags": ["animals"],
            "age_min": 3,
            "age_max": 6,
            "reading_level": "early",
            "language": "English",
            "format": "picture",
            "cover_url": "",
            "isbn": "111000000019",
        },
        {
            "title": "The Secret Stadium",
            "author": "R. Hale",
            "description": "Mystery in an old sports stadium.",
            "tags": ["mystery", "sports"],
            "age_min": 9,
            "age_max": 12,
            "reading_level": "middle",
            "language": "English",
            "format": "chapter",
            "cover_url": "",
            "isbn": "111000000020",
        },
        {
            "title": "Ocean Detective",
            "author": "K. Bell",
            "description": "Graphic novel mystery with sea creatures.",
            "tags": ["mystery", "animals"],
            "age_min": 8,
            "age_max": 12,
            "reading_level": "middle",
            "language": "English",
            "format": "graphic",
            "cover_url": "",
            "isbn": "111000000021",
        },
        {
            "title": "The Big Book of Bugs",
            "author": "E. Ford",
            "description": "Nonfiction picture book about insects.",
            "tags": ["animals", "science"],
            "age_min": 4,
            "age_max": 7,
            "reading_level": "early",
            "language": "English",
            "format": "picture",
            "cover_url": "",
            "isbn": "111000000022",
        },
        {
            "title": "Mystery at the Museum",
            "author": "S. Holland",
            "description": "Chapter book about a missing artifact.",
            "tags": ["mystery"],
            "age_min": 8,
            "age_max": 11,
            "reading_level": "middle",
            "language": "English",
            "format": "chapter",
            "cover_url": "",
            "isbn": "111000000023",
        },
        {
            "title": "Space Walkers",
            "author": "L. Novak",
            "description": "Kids train to become astronauts.",
            "tags": ["space", "science"],
            "age_min": 7,
            "age_max": 10,
            "reading_level": "middle",
            "language": "English",
            "format": "chapter",
            "cover_url": "",
            "isbn": "111000000024",
        },
        {
            "title": "Championship Dreams",
            "author": "N. Ali",
            "description": "Graphic novel about a youth baseball league.",
            "tags": ["sports"],
            "age_min": 9,
            "age_max": 12,
            "reading_level": "middle",
            "language": "English",
            "format": "graphic",
            "cover_url": "",
            "isbn": "111000000025",
        },
        {
            "title": "Forest Friends Mystery",
            "author": "J. Carter",
            "description": "Mystery with animal friends in the forest.",
            "tags": ["mystery", "animals"],
            "age_min": 6,
            "age_max": 9,
            "reading_level": "early",
            "language": "English",
            "format": "chapter",
            "cover_url": "",
            "isbn": "111000000026",
        },
        {
            "title": "Space Race Rangers",
            "author": "M. Alvarez",
            "description": "Chapter book about kids building rockets.",
            "tags": ["space", "science"],
            "age_min": 8,
            "age_max": 11,
            "reading_level": "middle",
            "language": "English",
            "format": "chapter",
            "cover_url": "",
            "isbn": "111000000027",
        },
        {
            "title": "The Secret of the Soccer Field",
            "author": "D. Park",
            "description": "A sports mystery with a missing trophy.",
            "tags": ["sports", "mystery"],
            "age_min": 8,
            "age_max": 12,
            "reading_level": "middle",
            "language": "English",
            "format": "chapter",
            "cover_url": "",
            "isbn": "111000000028",
        },
        {
            "title": "Sky Zoo",
            "author": "F. Bennett",
            "description": "Picture book about flying animals and a sky zoo.",
            "tags": ["animals", "fantasy"],
            "age_min": 3,
            "age_max": 6,
            "reading_level": "early",
            "language": "English",
            "format": "picture",
            "cover_url": "",
            "isbn": "111000000029",
        },
        {
            "title": "The Space Chef",
            "author": "R. Clarke",
            "description": "A funny picture book about cooking in space.",
            "tags": ["space"],
            "age_min": 4,
            "age_max": 7,
            "reading_level": "early",
            "language": "English",
            "format": "picture",
            "cover_url": "",
            "isbn": "111000000030",
        },
    ]

    result = db.books.insert_many(books)

    inventory = []
    for book_id in result.inserted_ids:
        inventory.append(
            {
                "book_id": book_id,
                "location_id": "main",
                "qty_available": random.randint(1, 5),
            }
        )

    db.inventory.insert_many(inventory)


if __name__ == "__main__":
    seed()
    print("Seeded books and inventory")
